use_frameworks!

target 'CYPLib_Example' do
  pod 'CYPLib', :path => '../'

  target 'CYPLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
